# Generated by Django 5.1.2 on 2024-10-26 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nimap', '0002_user_preferred_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='preferred_name',
        ),
    ]
