# Generated by Django 5.1.2 on 2024-10-26 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nimap', '0005_project_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='created_by',
        ),
    ]
